### PR TITLE
Use python3_host_prog if available

### PR DESCRIPTION
**Pull request by doronbehar**

### CODE REVIEW

**Review by peterbjorgensen — CHANGES_REQUESTED** [review]
Thanks a lot for the pull request, sorry for taking so long to reply.
I can merge in the pull request if you make it such that the fallback solution for when python3_host_prog is undefined is to just execute the `evinceSync.py` script (trusting the shebang line of the script). The command used to be hardcoded to `python3` and that created trouble for at least one user.

**Comment by doronbehar** [comment]
> The command used to be hardcoded to `python3` and that created trouble for at least one user.

Could you explain a bit more what was this problem? I also don't see a difference between using `python3` from `$PATH` and using `/usr/bin/env python3` as a shebang. As I see it, that's the point of using `/usr/bin/env` as a shebang - it consults `$PATH`.

**Comment by peterbjorgensen** [comment]
Here is the pull request that changed from using python3 directly to the shebang.
https://github.com/peterbjorgensen/sved/pull/9#issue-394982305
I am not sure why it would cause trouble for the nixpkg system, I agree that it's a bit odd.

**Comment by doronbehar** [comment]
Funny. I use NixOS as well and I understand why that PR was made - some NixOS users choose to make Nix handle all of their Vim/Neovim plugins. Doing this enables these NixOS users use a custom Python interpreter that Nix makes it include all the Python dependencies sved needs, without affecting the Python packages of the whole system.

I prefer not to use Nix to handle my Vim plugins, and now I am in a problem and I don't want to install globally the Python deps sved needs and now I'm in a problem :). I do think though, that it's reasonable for even non-nixos users to set to their `g:python3_host_prog` to a Python interpreter in an isolated environment they manage with `pipx` for example.

What if `sved` would have supported a boolean flag such as `g:sved_use_python3_host_prog` or it would use a `g:sved_python3_host_prog` that would be used only if not empty? Would that be acceptable? I will take care of documentation as well.

**Comment by peterbjorgensen** [comment]
I am happy that you understand the issue, because I still don't really understand the difference between `python3` and `/usr/bin/env python3` as they will both use the interpreter in `$PATH`.
I think the best solution would be to use the `g:python3_host_prog` variable if it is set, but if it is not set it should go back and execute the script and trusting the shebang line. I guess most people will expect plugins etc. to use the python interpreter set in `g:python3_host_prog`, so I don't think we need an additional flag.

**Comment by doronbehar** [comment]
> because I still don't really understand the difference between `python3` and `/usr/bin/env python3` as they will both use the interpreter in `$PATH`.

There is a difference in NixOS due to our build system - it patches all python shebangs in the packages it builds with a shebang of a specific interpreter - an interpreter that has the dependencies sved needs. If `tex_evinceSync.vim` uses either plain `'python3'` or `g:python3_host_prog`, the specific interpreter Nix sets, isn't used.

Hence I'm still left with a problem - some Nix users want to use the patched interpreter NixOS' build system sets, and some Nix users like me wish to use the `g:python3_host_prog` as the interpreter..

It's OK if you won't accept a patch as I suggested earlier, I can live with that.

**Comment by peterbjorgensen** [comment]
Thanks, it is more clear to me now. The Nix way of patching in a different interpreter in the shebang line seems like a way of asking for trouble. I do think we should respect the python provider configuration so your pull request makes sense. I might change it such that it uses `g:python3_host_prog` if it is set but falls back to the old behaviour of trusting the shebang if it is not set, if it can be done in a clean way. Thanks again for submitting the pull request.

**Comment by doronbehar** [comment]
> The Nix way of patching in a different interpreter in the shebang line seems like a way of asking for trouble.

Most of the times it doesn't cause troubles :).

> I do think we should respect the python provider configuration so your pull request makes sense. I might change it such that it uses `g:python3_host_prog` if it is set but falls back to the old behaviour of trusting the shebang if it is not set, if it can be done in a clean way.

I agree with you but this will break things on Nixpkgs, let's cc @symphorien as the author of https://github.com/peterbjorgensen/sved/pull/9 and https://github.com/NixOS/nixpkgs/pull/54590 Perhaps @teto would like to join the discussion as well.

To summarize the situation:

I don't use Nix to manage my Vim / Neovim plugins and I don't wish to do it, ([link to docs](https://nixos.org/manual/nixpkgs/unstable/#managing-plugins-with-vim-packages)). I use Gnome and I wish to use this plugin with `g:python3_host_prog` with the required python dependencies defined via nix thanks to `extraPython3Packages` argument. I don't need to wrap it also with `wrapGAppsHook` because on Gnome I have the required environment variables set anyway.

Somehow I managed to convince @peterbjorgensen - author of `sved` that using `g:python3_host_prog` makes more sense in comparison to just using the shebang. However, applying this change will break things on Nixpkgs, unless @peterbjorgensen will agree to introduce another variable such as `g:sved_use_python3_host_prog`, or we'll apply a patch in Nixpkgs reverting to the current behavior.

Another solution for Nixpkgs users could be this (perhaps hard to implement): If `sved` is enabled, make somehow the `g:python3_host_prog` be a Python interpreter wrapped with `wrapGAppsHook`.

**Comment by doronbehar** [comment]
I pushed a version of this patch which uses the shebang if

**Comment by doronbehar** [comment]
> Are you saying that there are cases where `g:python3_host_prog` _is_ set but the user still wants to use the python interpreter in the shebang line?

Correct, that's exactly what happens in Nixpkgs. Nix sets both `g:python3_host_prog` which should be suitable for most Python based plugins, without using Nix packages of vim plugins. For this plugin specifically, the Nix package wraps `evinceSync.py` with additional required Gnome related environment variables that some Nix users need. Personally I don't need these env vars and I wish to not use the Nix package of sved. Hence there's a conflict between me and other Nix users that want to use this plugin with the Nix package.

**Comment by peterbjorgensen** [comment]
@symphorien I will merge this. We should follow the python3_host_prog convention. I notify you because it might break your nix package.

**Pull request merged**
